name = "OneDly Project"
license = "MIT"
licenselink = "https://github.com/cdeck3r/OneDly-Theme/blob/master/LICENSE.md"
description = "Theme for documenting OneDly project."
homepage = "https://github.com/cdeck3r/OneDly-Theme"
tags = ["documentation", "landing page", "opensource"]
features = ["github", "images" ]
min_version= 0.1

[author]
     name = "Christian Decker"

[original]
    author =  "Omar Abdelhafith"
    homepage = "https://github.com/nsomar/github-project-landing-page"
    repo = "https://github.com/nsomar/github-project-landing-page"

